# Generated by Django 2.1.4 on 2019-01-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('secondName', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('debtValue', models.FloatField(verbose_name='Задолженность')),
            ],
        ),
    ]
