# Generated by Django 2.1.4 on 2019-01-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtApp', '0002_auto_20190104_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['secondName', 'name'], 'verbose_name': 'Задолженность', 'verbose_name_plural': 'Задолженности'},
        ),
    ]
